project: 
  type: website
  output-dir: docs

website:
  title: "Alexis Gonzalez Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/products/report/starter-analysis-report.qmd
          - text: "R Coding Exercise"
            file: coding-exercise/coding-exercise.qmd
          - text: "CDC Data Exercise"
            file: cdcdata-exercise/cdcdata-excercise.qmd
    right:
      - icon: github 
        href: https://github.com/lexigonzal/alexisgonzalez-MADA-portfolio.git        
format:
  html:
    theme: quartz
    highlight: zenburn
    css: styles.css
    toc: FALSE